### PR TITLE
support new release tarballs

### PR DESCRIPTION
**Pull request by balmas**
@PonteIneptique @sunofmon not sure who this should go to....

### CODE REVIEW

**Review by PonteIneptique — COMMENTED** [review]
Everything seems fine.
Is there anyway to version modules in puppet ?

**Comment by balmas** [comment]
Yes you can set the version in the metadata. I haven't upped it. Would you
like me to?

**Comment by PonteIneptique** [comment]
That would be great :)

**Comment by balmas** [comment]
ok. done.

**Pull request merged**
